main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('plants/', views.plants_index, name='index'),
    path('plants/<int:plant_id>/', views.plants_detail, name='detail'),
    path('plants/create/', views.PlantCreate.as_view(), name='plants_create'),
    path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='plants_update'),
    path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='plants_delete'),
    path('plants/<int:plant_id>/add_watering/', views.add_watering, name='add_watering'),
    # associate a pot with a plant (M:M)
    path('plants/<int:plant_id>/assoc_pot/<int:pot_id>/', views.assoc_pot, name='assoc_pot'),
    # unassociate a pot and plant
    path('plants/<int:plant_id>/unassoc_pot/<int:pot_id>/', views.unassoc_pot, name='unassoc_pot'),
    path('plant/<int:plant_id>/add_photo/', views.add_photo, name='add_photo'),
    path('pots/', views.PotList.as_view(), name='pots_index'),
    path('pots/<int:pk>/', views.PotDetail.as_view(), name='pots_detail'),
    path('pots/create/', views.PotCreate.as_view(), name='pots_create'),
    path('pots/<int:pk>/update/', views.PotUpdate.as_view(), name='pots_update'),
    path('pots/<int:pk>/delete/', views.PotDelete.as_view(), name='pots_delete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', views.signup, name='signup'),
]

plantcollector/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

WATER = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('E', 'Evening')
)

class Pot(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('pots_detail', kwargs={'pk': self.id})

# Create your models here.
class Plant(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    pots = models.ManyToManyField(Pot)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'plant_id': self.id})

    def watered_for_today(self):
        return self.watering_set.filter(date=date.today()).count() >= len(WATER)


class Watering(models.Model):
  date = models.DateField('watering date')
  water = models.CharField(
    max_length=1,
    choices=WATER,
    default=WATER[0][0]
  )

  plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_water_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for plant_id: {self.plant_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Watering

class WateringForm(ModelForm):
  class Meta:
    model = Watering
    fields = ['date', 'water']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3
from .models import Plant, Pot, Photo
from .forms import WateringForm

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'plantcollector'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid credentials - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


def home(request):
  return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def plants_index(request):
    plants = Plant.objects.filter(user=request.user)
    # You could also retrieve the logged in user's plants like this
    # plants = request.user.plant_set.all()
    return render(request, 'plants/index.html', { 'plants': plants })

@login_required
def plants_detail(request, plant_id):
  plant = Plant.objects.get(id=plant_id)
  pots_plant_doesnt_have = Pot.objects.exclude(id__in = plant.pots.all().values_list('id'))
  watering_form = WateringForm()
  return render(request, 'plants/detail.html', {
    'plant': plant, 'watering_form': watering_form,
    'pots': pots_plant_doesnt_have
  })

@login_required
def add_watering(request, plant_id):
  form = WateringForm(request.POST)
  if form.is_valid():
    new_watering = form.save(commit=False)
    new_watering.plant_id = plant_id
    new_watering.save()
  return redirect('detail', plant_id=plant_id)

@login_required
def add_photo(request, plant_id):
	# photo-file was the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, plant_id=plant_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', plant_id=plant_id)

@login_required
def assoc_pot(request, plant_id, pot_id):
  Plant.objects.get(id=plant_id).pots.add(pot_id)
  return redirect('detail', plant_id=plant_id)

@login_required
def unassoc_pot(request, plant_id, pot_id):
  Plant.objects.get(id=plant_id).pots.remove(pot_id)
  return redirect('detail', plant_id=plant_id)

class PlantCreate(LoginRequiredMixin, CreateView):
  model = Plant
  fields = '__all__'
  # ['name', 'description', 'age']
  # success_url = '/plants/'

  # This method is called when a valid
  # plant form has being submitted
  def form_valid(self, form):
    # Assign the logged in user
    form.instance.user = self.request.user
    # Let the CreateView do its job as usual
    return super().form_valid(form)

class PlantUpdate(LoginRequiredMixin, UpdateView):
  model = Plant
  fields = ['name', 'description', 'age']

class PlantDelete(LoginRequiredMixin, DeleteView):
  model = Plant
  success_url = '/plants/'

class PotList(LoginRequiredMixin, ListView):
  model = Pot

class PotDetail(LoginRequiredMixin, DetailView):
  model = Pot

class PotCreate(LoginRequiredMixin, CreateView):
  model = Pot
  fields = '__all__'

class PotUpdate(LoginRequiredMixin, UpdateView):
  model = Pot
  fields = ['name', 'color']

class PotDelete(LoginRequiredMixin, DeleteView):
  model = Pot
  success_url = '/pots/'

main_app/templates/about.html
    {% extends 'base.html' %}
    {% block content %}
    <h1>About the Plant Collector</h1>
    <hr />
    <p>Hire the Plant Collector!</p>

    {% endblock %}
    <footer>All Rights Reserved, &copy; 2019 Plant Collector</footer>

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Plant Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper #33691e light-green darken-4">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;PlantCollector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'pots_create' %}">Add a Pot</a></li>
                        <li><a href="{% url 'pots_index' %}">View All Pots</a></li>
                        <li><a href="{% url 'plants_create' %}">Add a Plant</a></li>
                        <li><a href="{% url 'index' %}">View All My Plants</a></li>
                        <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                        <li><a href="{% url 'signup' %}">Sign Up</a></li>
                        <li><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container ">
        {% block content %}
        {% endblock %}
    </main>
  	 <footer class="page-footer #33691e light-green darken-4">
       <div class="right">All Rights Reserved, &copy; 2019 Plant Collector &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Plant</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' plant.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add Plant</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/pot_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Pot</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn #bcaaa4 brown lighten-3">
    <a href="{% url 'pots_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/pot_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Pot Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ pot.name }}</span>
        <p>Color: {{ pot.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'pots_update' pot.id %}">Edit</a>
        <a href="{% url 'pots_delete' pot.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/pot_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Pot</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn #bcaaa4 brown lighten-3">
  </form>
{% endblock %}

main_app/templates/main_app/pot_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Pot List</h1>

{% for pot in pot_list %}
  <a href="{% url 'pots_detail' pot.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ pot.name }}</span>
            <p>Color: {{ pot.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Plant Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ plant.name }}</span>
        <p>Description: {{ plant.description }}</p>
        {% if plant.age > 0 %}
          <p>Age: {{ plant.age }}</p>
        {% else %}
          <p>Age: Baby</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'plants_update' plant.id %}">Edit</a>
        <a href="{% url 'plants_delete' plant.id %}">Delete</a>
      </div>
    </div>
      <!-- Insert photo markup below this comment -->
      {% for photo in plant.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
      {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
      {% endfor %}
      <form action="{% url 'add_photo' plant.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn" value="Upload Photo">
      </form>

  </div>
  <div class="col s6">
    <form action="{% url 'add_watering' plant.id %}" method="post">
        {% csrf_token %}
        {{ watering_form.as_p }}
        <input type="submit" class="btn #bcaaa4 brown lighten-3" value="Add Water Date">
    </form>
    <br>
    {% if plant.fed_for_today %}
      <div class="card-panel teal-text center-align">{{plant.name}} has been watered for today</div>
    {% else %}
      <div class="card-panel red-text center-align">{{plant.name}} might be hungry</div>
    {% endif %}
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Water</th></tr>
      </thead>
      <tbody>
        {% for watering in plant.watering_set.all %}
          <tr>
            <td>{{watering.date}}</td>
            <td>{{watering.get_water_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ plant.name }}'s Pots</h3>
    {% if plant.pots.count %}
      {% for pot in plant.pots.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ pot.color }}">{{ pot.color }}</span> {{ pot.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Pots :(</h5>
    {% endif %}
  </div>
  <!-- Available pots will come after this line -->
  <div class="col s6">
    <h3>Available Pots</h3>
    {% if pots.count %}
      {% for pot in pots.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ pot.color }}">{{ pot.color }}</span> {{ pot.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_pot' plant.id pot.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{plant.name}} Already Has All Pots Available</h5>
    {% endif %}
  </div>
</div>
<!-- JS to create a date picker and init the meal dropdown -->

<script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

    var selectEl = document.getElementById('id_water');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Plant List</h1>

{% for plant in plants %}
<a href="{% url 'detail' plant.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ plant.name }}</span>
            <p>Description: {{ plant.description }}</p>
            {% if plant.age > 0 %}
                <p>Age: {{ plant.age }}</p>
            {% else %}
                <p>Age: baby</p>
            {% endif %}
        </div>
    </div>
    </a>
{% endfor %}

{% endblock %}